# Generated by Django 5.0.1 on 2024-01-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('time_created', models.DateField(auto_now_add=True, null=True)),
                ('time_updated', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
