# Generated by Django 5.0.2 on 2024-02-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_image', models.CharField(max_length=255)),
                ('content1', models.TextField(blank=True)),
                ('content2', models.TextField(blank=True)),
            ],
        ),
    ]
