# Generated by Django 5.0.2 on 2024-02-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='content2',
            new_name='li1',
        ),
        migrations.AddField(
            model_name='home',
            name='li2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='home',
            name='li3',
            field=models.TextField(blank=True),
        ),
    ]
