# Generated by Django 5.0.2 on 2024-02-07 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_grouppost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(max_length=255, upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('price', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='book.category')),
                ('group', models.ManyToManyField(blank=True, related_name='group_book', to='book.grouppost')),
            ],
        ),
    ]
